// Used only when the API is unreachable (offline dev, failed deploy).
// Reflects real identity so offline renders never expose wrong name.
export const fallbackProfile = {
  name: 'Hasibul Hasan',
  role: 'Software Engineer',
  tagline: 'Software Engineer · Est. 2022',
  bio: 'Software engineer building web applications and internal tooling. Currently IT Engineer at BIFPCL — Bangladesh India Friendship Power Company Limited — shipping side projects in React, Node.js, and Firebase after hours. Open to remote full-stack roles worldwide.',
  location: 'Bangladesh · Remote',
  timezone: 'DHK',
  availability: 'Open to work',
  establishedYear: 2022,
  photoUrl: '',
  photoPath: '',
  email: 'hasibulhasan169@gmail.com',
  github: 'https://github.com/hasib41',
  linkedin: '',
  readcv: '',
  githubLabel: '/hasib41 ↗',
  linkedinLabel: '',
  readcvLabel: '',
  readcvKey: 'Personal',
  currentRole: 'IT Engineer',
  currentCompany: 'BIFPCL',
  yearsExperience: 2,
  shipped: 6,
  heroTagBefore: 'Software Engineer',
  heroTagAfter: 'Est. 2022',
  heroScrollHint: '↓ Scroll · Open to work · 2 min read',
  navWorkLabel: 'Work',
  navExperienceLabel: 'Experience',
  navStackLabel: 'Stack',
  navContactLabel: 'Contact',
  scanTitle: 'The 60-second scan',
  workEyebrow: 'Selected work',
  workTitleBefore: 'Shipped things',
  workTitleItalic: 'with',
  workTitleAfter: 'shipping dates.',
  workSubtitle: '',
  nowEyebrow: 'Currently',
  nowTitleBefore: 'Working',
  nowTitleItalic: 'on',
  nowTitleAfter: ', reading, thinking about.',
  nowBlurb: '',
  nowTitle: 'This month',
  nowSub: 'Focus · Deep work · Shipping',
  experienceEyebrow: 'Experience',
  experienceTitleBefore: 'Where I have',
  experienceTitleItalic: 'worked',
  experienceTitleAfter: '& what I shipped.',
  experienceSubtitle: '',
  stackEyebrow: 'Stack',
  stackTitleBefore: 'Breadth,',
  stackTitleItalic: 'with',
  stackTitleAfter: 'a few deep wells.',
  stackSubtitle: '',
  testimonialEyebrow: 'Word on the street',
  contactEyebrow: 'Contact · Open for hire',
  contactCtaBefore: "Let's",
  contactCtaItalic: 'talk',
  contactCtaAfter: '→',
  footerTagline: 'Handcrafted in Bangladesh',
  footerVersion: 'v1.0 · no cookies, no tracking',
};

export const fallbackProjects = [];
export const fallbackExperience = [];
export const fallbackStack = [];
export const fallbackTestimonials = [];
export const fallbackMetrics = [];
export const fallbackNow = [];
export const fallbackTicker = [];
